### ISSUE TITLE
Win 10 Pro 21H1 19043.782, no Mined block in explorer

### ISSUE THREAD

**Issue by Magby123** [CryptoKasm/9c-swarm-miner#1]
Hi, I have follow instructions  under win 10pro - with no errors.
![111](https://user-images.githubusercontent.com/78310118/106388668-b2eb5480-63f0-11eb-9004-7370d7667bde.png)
But miner works about 15 mins and during that time , or after - no blocks  get in Explorer (under public key) and ofc i checked "settings conf" for Public and Private key...
  It was tested not 1 time with different options( ram limits, and number of miner) the rusult the same - after about 15 mins you got spamm of Append fail and no  Block\Transactions in explorer for miner use.

**Comment by CryptoKasm** [comment]
Everything in the image you posted looks correct. The issues you are seeing, are related to the docker image itself. My scripts simply automates: installing dependencies, setting up docker via docker-compose, and refreshing the snapshot. All output after docker containers start would be in reference to the headless miner image located here:
https://github.com/planetarium/NineChronicles.Headless

**Comment by Magby123** [comment]
ok thnx, will go there ;)
